name: build base container

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./YOEP/Dockerfile.base
        push: false
        tags: devcontainer-base-yoep:${{ steps.extract_branch.outputs.branch }}

# This uses bash variable expansion magic to do the lowercase: https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html
    - name: Push
      shell: bash
      run: docker push ghcr.io/${GITHUB_ACTOR,,}/devcontainer-base-yoep:${{ steps.extract_branch.outputs.branch }}
      id: docker_push

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}